### PR TITLE
Updated NUI to use gestalt 7

### PR DESCRIPTION
**Pull request by BenjaminAmos**
Most of the changes in this pull request involve updating NUI to use the new gestalt namespace, as well as changing the usages of a couple of re-named methods. To avoid conflicts with the 1.0.0 version of NUI, which still uses an older incompatible version of gestalt, the version number is now 2.0.0. There should be no functional UI changes in this pull request, apart from using a newer version of gestalt.

This is needed for MovingBlocks/DestinationSol#536.

### CODE REVIEW

**Comment by Cervator** [comment]
Good questions there, and I've wondered some myself. The initial release reworking I did on TeraNUI since good candidate for experimentation just gets the releases off `master` based on a simple check on the version string (same as and in fact copy pasted from Gestalt)

My next goal along with this PR was going to be how to handle releases in parallel and would likely involve checking a branch pattern beyond `master` in Jenkins, so a branch like `release_v1.2.3` (or maybe `rc_v1.2.3` ? The moment it finally releases and gets tagged the branch could be deleted) would **also** qualify for publishing snapshots and ultimately a separate release, limited to a version matching the branch name (to avoid oopsies like making a release branch without changing the version in code)

That doesn't solve maintaining the two releases though. That reminds me a little of how the https://github.com/MovingBlocks/CrashReporter actually has little mini-wrappers for Terasology and DestSol yet they live in the same branch, there's only one build, but it publishes a generic binary + the game specific wrappers, and each game just targets that to get its unique properties and such. You might be able to resolve the different Gestalt dependencies that way but _not_ readily the differing package names and actual logic changes, so that may not help :-(

After I pushed forward a bit here I aimed to apply the lessons learned to the Gestalt repo, as yeah, it got a little messy with the branches and such over time. While we could probably come up with all kinds of clever ways to handle parallel streams I'm not sure either project is likely to change enough to throw more logistics at it, maybe it would be enough to just manually backport / pull forward changes made in one stream to the other. https://xkcd.com/974/

Will try to first just support parallel releases at all, then poke at Gestalt, and see how things are looking by then on how to handle ongoing development. Surely we'll need it elsewhere in the future, so it'll be good to have some best practices. More ideas and/or experimentation definitely appreciated 👍

**Comment by skaldarnar** [comment]
I was rather hoping for a simple markdown document guiding me through some steps instead of full automation 🙄 🙈 I don't think that we should attempt templating the NUI code to generate artifacts for gestalt v5 and v7. A simple guide on **how to merge and back-port changes** would be enough. 

Also, I'm not sure we need automated parallel releases (not exactly sure what you mean by "parallel releases" tbh). I'd think we'll have **release branches** from which we do releases for `teranui-1.x` and `teranui-2.x` respectively. This my require to commands or actions by the maintainer, all fine as long as it is documented. 

I'd prefer a git-tag based approach, but I'm not sure whether we are there yet 🤓

**Comment by Cervator** [comment]
Oh certainly agreed on a proper write-up in some doc. I don't personally have anything firm I can write up yet, but we'll get there at some point soon I'm sure. Right now mostly just thinking out loud.

Yeah with parallel releases feel free to interpret as some sort of release branch setup, didn't have anything special or elaborate in mind. Point being we'll occasionally work on either of the two lines. Hopefully we can do something simple like cherry picking commits to backport.

**Comment by Cervator** [comment]
Small side-comment: I've done a from-local snapshot release of this branch to Artifactory so `2.0.0-SNAPSHOT` is available for further DestSol tinkering. Will get back to a more formal release process when able and sort out how to merge this by then :-)

**Comment by skaldarnar** [comment]
@BenjaminAmos any idea what might be off with this?

```
> Task :nui:test FAILED

:nui:test (Thread[Execution worker for ':',5,main]) completed. Took 3.735 secs.


FAILURE: Build failed with an exception.


* What went wrong:

Execution failed for task ':nui:test'.

> Could not resolve all files for configuration ':nui:testRuntimeClasspath'.

   > Could not find com.android.support:support-annotations:28.0.0.

     Searched in the following locations:

       - file:/home/jenkins/.m2/repository/com/android/support/support-annotations/28.0.0/support-annotations-28.0.0.pom

       - https://jcenter.bintray.com/com/android/support/support-annotations/28.0.0/support-annotations-28.0.0.pom

       - https://repo.maven.apache.org/maven2/com/android/support/support-annotations/28.0.0/support-annotations-28.0.0.pom

       - http://artifactory.terasology.org/artifactory/virtual-repo-live/com/android/support/support-annotations/28.0.0/support-annotations-28.0.0.pom

       - http://maven.snplow.com/releases/com/android/support/support-annotations/28.0.0/support-annotations-28.0.0.pom

     Required by:

         project :nui > org.terasology.gestalt:gestalt-module:7.0.3

         project :nui > org.terasology.gestalt:gestalt-asset-core:7.0.3

         project :nui > org.terasology.gestalt:gestalt-module:7.0.3 > org.terasology.gestalt:gestalt-util:7.0.3

```

@pollend added some test dependencies in #8, maybe that makes problems now?

**Comment by BenjaminAmos** [comment]
I had not included any tests previously, so I hadn't tried running them before. Gestalt 7 makes use of some annotations from the Android support libraries (https://developer.android.com/studio/write/annotations) in order to enforce certain warnings with the linter (like the `@RequiresApi` annotation [here](https://github.com/MovingBlocks/gestalt/blob/e0ef2838fc94a06a184eefb0fa29285c46fe83c1/gestalt-module/src/main/java/org/terasology/gestalt/module/ModuleFactory.java#L69)). Unfortunately those annotation libraries are only found in the `google` maven repository. The libraries compile fine without them but when it comes to the tests then they are required on the classpath. The simplest fix for this is to include the `google` repository in the build script and I've just pushed a commit to do that. The tests don't produce that error for me after adding the repository in.

**Pull request merged**
