### PR TITLE
Added NUI code extracted from Terasology (relates to Terasology#3819)

### PR DESCRIPTION
**Pull request by BenjaminAmos**
### Description
This pull request contains code extracted from the `org.terasology.rendering.nui` package in the Terasology codebase. It also contains some of the input classes taken from the `org.terasology.input` package, which are used within the NUI code. All references to the package `org.terasology.rendering.nui` have been changed to `org.terasology.nui`.

### Overview of API changes
 - Changed package from `org.terasology.rendering.nui` to `org.terasology.nui`
 - `Font` has been changed from an asset class to an interface
 - `Texture` has been removed and `TextureRegion` has been re-named to `UITextureRegion`
 - The `drawMesh` and `drawMaterial` methods have been removed from the `Canvas` interface. Replacements for these methods can be found in the `org.terasology.rendering.nui.CanvasUtility` class.
 - Any input events used in NUI from the `org.terasology.input.events` package have been replaced with ones from the `org.terasology.nui.events` package.
 - All of the dependent classes are currently included within the nui package for testing purposes (many of them need to be moved to TeraMath and other related repositories)
 - Most of the `CoreRegistry` or `Assets` usages have been replaced with constructor parameters, however there may be some instances where no replacement has been made
 - The `UIFormat`, `UIDeltaFormat` and `UISkinFormat` are JSON de-serialisers, which are implementation specific classes. Porting them would imply that a JSON-based format would need to be used for UI files. They are instances of `AbstractAssetFileFormat`, which is used by gestalt to separate asset implementation from asset data. These have been left in the Terasology codebase and not ported to NUI.
 - `Translator` is present as an abstraction over Terasology's `TranslationSystem`, which is used for translating strings. With this, the built-in NUI widgets can retain internationalisation support.
### Package Structure

Package | Description 
--------- | -----------
 `org.terasology.nui` (nui) | Contains the portable core code for NUI
 `org.terasology.input` (nui-input) | Contains input code extracted from Terasology that is used by NUI
 `org.terasology.reflection` (nui-reflect) | Contains reflection utilities extracted from Terasoloy for use in NUI (used in `org.terasology.nui.properties.PropertyProvider`)
### Duplicated classes
The following classes currently exist in both Terasology and NUI:
 - Classes within the `org.terasology.input` namespace.

### Notes
 - This depends on https://github.com/MovingBlocks/TeraMath/pull/63.
 - This relates to MovingBlocks/Terasology#3819

### CODE REVIEW

**Comment by skaldarnar** [comment]
@BenjaminAmos this PR looks really nice. Will try to take some time to look at it in detail over the next days. 
One thing to ask afront: could you double check whether there have been changes to NUI in the engine repo since January 16 that are not included here? 

I need to catch up on some of the terms and technical details, though. Would be nice if you could be available on Discord and be ready to answer some of my questions 😅 

> All of the dependent classes are currently included within the nui package for testing purposes (many of them need to be moved to TeraMath and other related repositories)

Should they be moved to TeraMath or directly be ported to use JOML?

**Comment by BenjaminAmos** [comment]
Based on the changelog [here](https://github.com/MovingBlocks/Terasology/commits/develop/engine/src/main/java/org/terasology/rendering/nui), the only commit that should have affected NUI (instead of Terasology's code using NUI) is https://github.com/MovingBlocks/Terasology/commit/cfe8cec22a4080ad88869f70139cd833c01e7e35#diff-9f2e133f53dd756f34e7a8ddf80ec8e3.

I've re-based the Terasology code changes locally without any major conflicts, however the incorporation of JOML code over TeraMath has caused some issues. Terasology's Font class no longer compiles when the changes are added, as it now uses JOML's Vector2i class instead of TeraMath's. I could port NUI to use JOML as well, although I don't have any preference here. My port doesn't preserve the git history from the Terasology repository, as I hadn't really considered that at the time. It was mostly a job of copying files and modifying them until they compiled. I then tried to fix bugs when I found them.

The extracted NUI code is currently running with two seperate lines of development: [gestalt 5](https://github.com/BenjaminAmos/TeraNUI/tree/nui-extraction-merge) (this pull request) and [gestalt 7](https://github.com/BenjaminAmos/TeraNUI/tree/nui-extraction-gestalt7). I'd experimented with adding NUI into Destination Sol (changes [here](https://github.com/BenjaminAmos/DestinationSol/tree/nui-intergration)), which uses gestalt 7, rather than Terasology's gestalt 5 and so ported NUI to use it as well (using gestalt 7 in Terasology is possible however it requires quite a few engine changes to work due to large interim gestalt API changes involved). The code is in a seperate branch though, which appears to be getting slightly more bugfixes than the gestalt 5 one. I can try to backport some of those fixes though. It's been a couple of months since I've touched this code, although I am not aware of any extremely serious TODOs in the code that I need to fix. The code has incorporated the LibGDX back-end I wrote for NUI though, so either I will have to find a way to remove it from the git history or it will have to live in the TeraNUI repository as well. Do you mind if I leave it in there?

From memory though, NUI depended on certain elements of Terasology's codebase that were slightly less generic. The `org.terasology.input` package is used slightly by NUI, as well as the `org.terasology.math.Border` class. The border class was provisionally to be moved to TeraMath (see https://github.com/MovingBlocks/TeraMath/pull/63), however it can be moved back-into NUI's codebase directly instead. So far as I know, the class does not belong in JOML (https://github.com/MovingBlocks/Terasology/pull/3819#issuecomment-570580455), so I was not planning to submit it there. I think that I analysed the dependencies in more detail at https://github.com/MovingBlocks/Terasology/issues/2307#issuecomment-573408627. I need to update the information provided slightly though to describe the new package included with NUI for now (`nui-libgdx`).

**Comment by skaldarnar** [comment]
Thanks for the detailed explanation 💚 

> The code has incorporated the LibGDX back-end I wrote for NUI though, so either I will have to find a way to remove it from the git history or it will have to live in the TeraNUI repository as well. Do you mind if I leave it in there?

Doesn't sound too worrysome for me - and our git history is not really nice to look at anyways, so I wouldn't worry too much about it.

> The border class was provisionally to be moved to TeraMath (see MovingBlocks/TeraMath#63), however it can be moved back-into NUI's codebase directly instead.

I don't understand the details good enough to have a preference here. If the border would be used somewhere else, too, it might be better off in TeraMath. If it is only used for NUI include it here.

**Comment by keturn** [comment]
Gradle notes:

1) I've just found out it helps for each subproject to have its `project.group` set. Each of them has a `groupId` set in their `publication` configuration, but apparently gradle composite builds don't look that deeply when deciding what dependencies the included build provides.

You can do that in each subproject's build.gradle or in an `allprojects` section of the root build.gradle, but it looks like this branch has chosen to do away with using `allprojects`.

2) In order to work as a Terasology dependency, each of the java subprojects will need a 

```java
    targetCompatibility(JavaVersion.VERSION_1_8)
```

in their `java { }` configuration. Otherwise I guess it defaults to whatever jdk you happen to be on at the time, which doesn't convince the terasology build that it will work for jdk 8.

Those seem to be the critical bits. One other bit of tidying is the SourceSet configuration:

```groovy
sourceSets {
    main {
        java
    }
}
```

It's not clear if this does anything? By applying the `java-library` plugin to the project, I think it already sets up a `main` source set that compiles java sources by default.

**Comment by BenjaminAmos** [comment]
I'm not familiar with composite builds, so I wasn't aware of those things being needed. Source and target compatibility information has been added, alongside removing the `sourceSets`. As I haven't used composite builds sucessfully before, I can't test if it works but I've added the groups as you asked and hopefully that will work.

**Comment by keturn** [comment]
Terasology uses joml 1.9.25 now, and there were breaking changes between 1.9.24 and 1.9.25: https://github.com/JOML-CI/JOML/releases/tag/1.9.25 :disappointed: 

In addition, this means we need to add [strict version requirements](https://docs.gradle.org/current/userguide/rich_versions.html#sec:strict-version) wherever we define a joml dependency in gradle, because we can't let gradle assume that it's okay to satisfy a requirement for 1.9.24 with a 1.9.25 version.

**Comment by Cervator** [comment]
Actually, on second thought, I think I fixed @keturn's concern by accident already. The `group` is set in the new `common.gradle` for each project, which is then the default value used for the published `groupId` the setting of which I then deleted since it isn't needed anymore.

**Pull request merged**
