### PR TITLE
gestaltv7 compability for NUI 2.0

### PR DESCRIPTION
**Pull request by DarkWeird**
#### Contains
* some changes cherry picked from v1.0.0 ( Colorc, RectUtitlity#map)
   For Terasology engine compability
* moving package from `org.terasology.input` to `org,terasology.nui.input` 
   Cleaning `org.terasology` package 
   Compability for  gestaltv7's package module
* moving package from `org.terasology.reflection` to `org.terasology.nui.reflection`
   Cleaning `org.terasology` package 
   Compability for  gestaltv7's package module

### CODE REVIEW

**Comment by keturn** [comment]
This is from September's gestalt-v7 proposal. I expect it's still relevant, is it still mostly up-to-date?

**Comment by jdrueckert** [comment]
> This is from September's gestalt-v7 proposal. I expect it's still relevant, is it still mostly up-to-date?

I'd hope @DarkWeird can answer that?

**Comment by DarkWeird** [comment]
> > This is from September's gestalt-v7 proposal. I expect it's still relevant, is it still mostly up-to-date?
> 
> I'd hope @DarkWeird can answer that?

@keturn 
Yeah. It is up to date.

Needs another engine's pr for update imports.
(Together with gestaltv7 pr)

**Comment by skaldarnar** [comment]
Is this porting over everything that is needed, or only some partial list?

For reference, this is how the two branches are diverging...

```
* 6a27464 feat(flexibleconfig): UI for editing arbitrary types and AutoConfigs (#36)
* 4488cf0 chore: prepare snapshot builds for 1.5.0
* 25ba115 (tag: v1.4.0) release: version 1.4.0
* bac6a5a chore: use newly released joml-ext v0.1.0 (#40)
* 0b65cf1 chore: trigger build with new joml-ext SNAPSHOT
* 5429dad feat(JOML): migrate joml to 1.10.0 and 1.0.0-SNAPSHOT for geometry (#39)
* 5762bbd chore: prepare next snapshot for 1.4.0
* 4b9733d (tag: v1.3.1) release: version 1.3.1
* ee8af75 fix: moving while typing in console or chat (TS) (#35)
* 8fa207a chore: prepare next snapshot for 1.4.0
* 55f074e (tag: v1.3.0) release: version 1.3.0
*   7f66723 Merge pull request #24 from MovingBlocks/topic/lwjgl3
|\  
| *   356aae2 Merge pull request #32 from MovingBlocks/topic/lwjgl3-compile-errors
| |\  
| | * a1034de correct compile errors for LibGDXKeyboard
| |/  
| *   21a2d82 Merge branch 'release/v1.x' into topic/lwjgl3
| |\  
| |/  
|/|   
* | 82556b6 feat: add new prop "overrideChildEnabledProp" to AbstractWidget (#29)
* | 8bfd1db fiy(miglayout): `setRowConstraints` uses col constraints (#25)
| * 22e7b69 chore(lwjgl3): Fix nui versioning.
| * ab32b35 Bump up version
| * e410156 feat(lwjgl3): split keyboard input to raw input and text input. Returns MouseDevice#getPosition
|/  
* 0642317 chore: version bump
* 41b80fe release: version 1.2.0
* be9da9d fix: restore type parity from when NUI was in the Terasology engine (int then, byte now)
* 86aa22f fix Color(float,float,float,float) (#21)
* c797577 chore: bump next version scope to minor, tiny Gradle cleanup
* 03abcde tweaked canvas render
* 0b33510 remove new Color for operations
* 81c157a update imports
* 250a0e3 add rectangle test
* 596f6ad feature add map to RectUtility and readonly color
* 5eabc56 chore: prepare next snapshot for 1.1.1
* 4c9ea44 release: version 1.1.0
* 2445166 add missing clamp to Color#set*
* 85128bb test: test both set and alter methods for Color
* 2e6026a test: Add FontColorTest (from MovingBlocks/Terasology)
* 7be7f4c test: Add more ColorTests (from MovingBlocks/Terasology)
* 27fce2d test: Add LineTest (from MovingBlocks/Terasology)
* 58f4f67 fix: Explicitly compute rect from min and size in Line
* 47a3874 test: Add BorderTest; remove JOML conversions, fix assertions
* 77fc889 docs: Add JavaDoc for `createFromMinAndMax`
* 35b38ab fix: `createFromMinAndSize` clamps and validates result
* 9c88213 chore: Add math utility `addClampAtMax` for float
* 6abc996 feat: deep copy of EntityRef.copy (MovingBlocks/Terasology#4099)
* 24902bc chore: add info how to get TeraNUI for local testting
* 179c810 chore: prepare next snapshot for 1.1.0-SNAPSHOT
* b4c243a (tag: v1.0.0) release: version 1.0.0
| * 7e9c5d5 (origin/master, master) fiy(miglayout): `setRowConstraints` uses col constraints (#26)
| * e1f7918 docs: Add JavaDoc for `createFromMinAndMax`
| * a4a74e3 fix: `createFromMinAndSize` clamps and validates result
| * b228db2 chore: Add math utility `addClampAtMax` for float
| * 40b4a18 chore: add info how to get TeraNUI for local testting
| * 456edae chore: prepare next snapshot for 2.1.0-SNAPSHOT
| * 4f78131 (tag: v2.0.0) release: version 2.0.0
| * 926d327 Updated NUI to use gestalt 7 (#4)
|/  
* 2af3a7d chore: prepare multi releases (#11)
```

**Comment by keturn** [comment]
which two branches diverged? this vs the v2.0 branch, or the https://github.com/MovingBlocks/TeraNUI/commits/release/v1.x branch?

**Comment by keturn** [comment]
Now that #47 is merged as v3, where does that leave this?

[Here](https://github.com/MovingBlocks/Terasology/pull/4593#issuecomment-804389006) you said:

> I think use BSA's PR firsts, then provide support in nui-gestaltv7 module is better then synthetic module

**Comment by DarkWeird** [comment]
> Now that #47 is merged as v3, where does that leave this?
> 
> [Here](https://github.com/MovingBlocks/Terasology/pull/4593#issuecomment-804389006) you said:
> 
> > I think use BSA's PR firsts, then provide support in nui-gestaltv7 module is better then synthetic module
> 
> 

Next steps:
1. Close no related PR at TeraNUI(bug fixes from v1 to v2)
2. Rebase  related prs.
3. Integrate nui v3 to terasology (develop)
4. Switch nui-gestalt at gestaltv7 pr.

(Or skip 3)

Profits:
1. No repeating bugfixes
2. Switch should be easier
3. NuiV3 not syntetic module at TS and DestSol

**Comment by DarkWeird** [comment]
Obsolete after https://github.com/MovingBlocks/TeraNUI/pull/47

**Pull request closed without merging**
