### PR TITLE
build: upgrade gradle 6.5 -> 8.2.1

### LINKED ISSUE #57: upgrade to gradle 6.9.x (prep for gradle 7.x)
Gradle 7 has some features Terasology is interested in (e.g. version catalogs). Since the MovingBlocks/✳ libraries are often used in composite builds with Terasology, it seems like a good idea to keep their gradle versions from drifting too far apart.

I propose upgrading all the libraries to the latest in the 6.x line (currently 6.9.0) and fixing whatever deprecation warnings crop up there. That should give us a smooth path to then adopting Gradle 7.

### PR DESCRIPTION
**Pull request by keturn**
Relates to https://github.com/MovingBlocks/Terasology/pull/5109
Relates to https://github.com/MovingBlocks/Terasology/pull/4653

### Contains

* Updating gradle from 6.5 -> 8.2.1
* Updating gradle's files for which became invalid

### How to test

* run `gradlew build` -> should build TeraNUI
* we could further test it in combination with Terasology (`groovyw lib get TeraNUI && gradlew jar game`)

### Remarks

Java 20 is not yet supported, see https://github.com/gradle/gradle/issues/23488.

Closes #57

### CODE REVIEW

**Comment by jdrueckert** [comment]
@BenjaminAmos @skaldarnar should we backport this to `release/v2.x` and `release/v1.x` branches?

**Comment by jdrueckert** [comment]
> The new Gradle wrapper jar corresponds with Gradle [`6.9.2`](https://gradle.org/release-checksums/#6.9.2).

How would I update this? Just find and copy-paste the 8.2.1 version of it? 🤔 
Or is there some gradle command I can run so it updates it itself?

**Comment by BenjaminAmos** [comment]
Destination Sol is actually using a snapshot from the `preview/v4.x-SNAPSHOT` branch because of Gestalt 8. I can handle backporting to there. I do not believe that either the `release/v1.x` or the `release/v2.x` branch is used anywhere anymore.

**Comment by BenjaminAmos** [comment]
> > The new Gradle wrapper jar corresponds with Gradle [`6.9.2`](https://gradle.org/release-checksums/#6.9.2).
> 
> How would I update this? Just find and copy-paste the 8.2.1 version of it? 🤔 Or is there some gradle command I can run so it updates it itself?

You can use the `gradlew wrapper` command to update the wrapper itself. I linked to the [release checksums page](https://gradle.org/release-checksums/) above just in-case somebody wished to verify that the wrapper jar was identical to the official wrapper.

**Pull request merged**
